nodeLinker: pnp
pnpMode: strict

# 支持原生模块（如 esbuild、rollup 等）
supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

# 包扩展配置
packageExtensions:
  "@vitejs/plugin-react@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"
  "rollup@*":
    dependencies:
      "@rollup/rollup-win32-x64-msvc": "*"
